### ISSUE TITLE
GatewayError: Do not include endpoint URL

### ISSUE THREAD

**Issue by threema-danilo** [dbrgn/threema-gateway-rs#51]
URLs could contain API secrets, so they should not be written to a log.

Steps to reproduce: Validate credentials with an invalid endpoint URL. This will result in a timeout, with the URL contained in the error message. Instead, only include the hostname.

**Comment by dbrgn** [comment]
Steps to reproduce (in an example):

```
     // Look up ID
-    let api = ApiBuilder::new(from, secret).into_simple();
+    let api = ApiBuilder::new(from, secret)
+        .with_custom_endpoint("https://exasdfasdfasdfample.com")
+        .into_simple();
```
